version: "3"
services: 
  postgresql:
    image: postgres:13
    container_name: 'postgresql_tienda'
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eliascolon98
      - POSTGRES_DB=tiendabd
    ports: 
      - 5432:5432
  nodeapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node
    container_name: 'app_tienda'
    environment: 
      # - DB_HOST=
      DATABASE_URL: "postgres://postgres:eliascolon98@db:5432/tiendabd"
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - postgresql
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
# volumes:
#   postgresql:
#     external: false