version: "3"
services: 
  postgresql:
    image: postgres:13
    container_name: 'postgresql_tienda'
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eliascolon98
      - POSTGRES_DB=tiendabd
    ports: 
      - 5432:5432
  app_tienda:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node
    container_name: 'app_tienda'
    environment: 
      - DB_HOST=localhost
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - postgresql
# volumes:
#   postgresql:
#     external: false